---
- name: Mount AWS FSx Filesystems on Linux
  hosts: fsx_hosts
  become: true
  vars_files:
    - vars/fsx.yml

  tasks:
    - name: Ensure NFS utilities are installed
      yum:
        name: nfs-utils
        state: present

    - name: Create mount directories for each FSx instance
      file:
        path: "{{ item.mount_point }}"
        state: directory
        mode: '0755'
      loop: "{{ fsx_instances }}"

    - name: Mount FSx filesystems
      mount:
        path: "{{ item.mount_point }}"
        src: "{{ item.fsx_path }}"
        fstype: nfs
        opts: defaults,_netdev
        state: mounted
      loop: "{{ fsx_instances }}"

    - name: Ensure FSx mounts persist on reboot
      mount:
        path: "{{ item.mount_point }}"
        src: "{{ item.fsx_path }}"
        fstype: nfs
        opts: defaults,_netdev
        state: present
      loop: "{{ fsx_instances }}"
